spring:
  application:
    name: java-scheduler

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/java_scheduler}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate