spring:
  main:
    web-application-type: none
    
  application:
    name: omnicron

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/omnicron}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

worker:
  scheduler:
    interval: 5000
    batch-size: 10
  processor:
    thread-count: 3
  poller:
    interval: 5000
    batch-size: 20
    lock-duration: 30s
  kubernetes:
    namespace: default
    ttlSecondsAfterFinished: 3600
